In [1]:
import numpy as np # type: ignore


In [2]:
# Constract a matrix below

matrix = np.array([[1 ,0.2 ,0.5],[0.2 ,1 ,0.8],[0.5, 0.8 ,1]])


(i) Compute the inverse of the matrix(transpose)

In [3]:
#(i) we have to first get the Transpose before the inverse

transpose_of_matrix = matrix . T
print(transpose_of_matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
#inverse of a matrix Transpose

inverse_of_matrix = np.linalg.inv(transpose_of_matrix)
print(inverse_of_matrix)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


(ii) Determinant of a matrix

In [5]:
#Determinant of a matrix
determinant_of_matrix = np.linalg.det(matrix)
print(determinant_of_matrix)

0.2299999999999999


(iii)  Decomposing  the matrix 

In [6]:
# Decomposing  the matrix 
from scipy.linalg import lu # type: ignore

In [7]:
#performing Lu Decomposition which indudes permutation P,lower L and upper U from the above matrix
P, L, U = lu(matrix)

In [8]:
# Print  P (Permutation) Decomposition
print("The Permutation Matrix (P) is:")
print(P)

The Permutation Matrix (P) is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#L (Lower) Decomposition
print("The Lower Triangular Matrix (L) is:")
print(L)

The Lower Triangular Matrix (L) is:
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]


In [10]:
#U (Upper) Decomposition
print(" The Upper Triangular Matrix (U) is:")
print(U)

 The Upper Triangular Matrix (U) is:
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


(iv) Transforming a matrix

In [11]:
# The matrix can be transformed in many ways as below
# a) Transpose of the matrix
transpose_matrix = matrix.T
print("The Transpose of the Matrix is:")
print(transpose_matrix)

The Transpose of the Matrix is:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [12]:
# b) Scaling the matrix by a factor of 2
scaled_matrix = 2 * matrix
print("The Scaled Matrix (by factor of 2) is:")
print(scaled_matrix)

The Scaled Matrix (by factor of 2) is:
[[2.  0.4 1. ]
 [0.4 2.  1.6]
 [1.  1.6 2. ]]


In [13]:
# c) Matrix Multiplication (matrix dot product with itself)
multiplied_matrix = np.dot(matrix, matrix)
print("The Matrix Multiplication is:")
print(multiplied_matrix)


The Matrix Multiplication is:
[[1.29 0.8  1.16]
 [0.8  1.68 1.7 ]
 [1.16 1.7  1.89]]
